apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: express-app-alex-chris
spec:
  params:
  - description: Source code repository
    name: source-repo
    type: string
  - description: Docker image repository
    name: image-repo
    type: string
  tasks:
  - name: clone-repository
    params:
    - name: url
      value: $(params.source-repo)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: pipeline-shared-data
  - name: create-image
    params:
    - name: IMAGE
      value: $(params.image-repo):$(tasks.clone-repository.results.commit)
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  workspaces:
  - name: pipeline-shared-data
