apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-app-alex-chris-pipelinerun-
spec:
  params:
  - name: source-repo
    value: https://github.com/cloud-native-garage-method-cohort/express-app-alex-christopher.git
  - name: image-repo
    value: quay.io/chrisley7506/express-app-alex-chris
  pipelineRef:
    name: express-app-alex-chris
  serviceAccountName: build-bot
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi