apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
  - description: Source code repository
    name: source-repo
  - description: Precise SHA of the commit to build
    name: sha
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: express-sample-app-
    spec:
      params:
      - name: app-name
        value: express-sample-app
      - name: image-repo
        value: quay.io/chrisley7506/express-sample-app
      - name: source-repo
        value: https://github.com/cloud-native-garage-method-cohort/christopher-ley-express-app
      - name: sha
        value: $(tt.params.sha)
      pipelineRef:
        name: nodejs
      serviceAccountName: build-bot
      workspaces:
      - name: pipeline-shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: gitops-repository
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
